### ISSUE TITLE
Git ignores wrong Cache folder

### ISSUE THREAD

**Issue by Atyc** [raulir/bccms#227]
!/system/libraries/Cache/

**Comment by raulir** [comment]
This is cache related section in .gitignore. This shouldn't ignore this folder?

```
application/cache/*
!application/cache/index.html
!application/cache/.htaccess

/cache/*
!/cache/index.html
```

**Comment by Atyc** [comment]
Apparently it shouldn't be ignored but it happened every time in my last 4-5 installations.

**Comment by raulir** [comment]
Weird stuff, as this is clearly not ignored here:

![image](https://user-images.githubusercontent.com/7125761/35918712-b1c4091c-0c0a-11e8-9bbf-d6e91e998204.png)

I'll add your path to the .gitignore, as this won't do any harm.

**Comment by Atyc** [comment]
It doesn't happen when I clone this repository.
Only when I download the archive from Github and create a new local repo with it.
This is what I usually do, because I don't need the entire GIT history of BCCMS when I start a new website.
![screen shot 2018-02-07 at 13 35 29](https://user-images.githubusercontent.com/9115386/35919136-15d624c0-0c0c-11e8-88ac-81144903d607.png)

**Comment by raulir** [comment]
This list of ignored files is not very similar, what .gitignore contains in repo ...

**Comment by raulir** [comment]
Downloaded as zip and gitignore there looks ok too.

From where this room_black_icon3.png is coming from?

**Comment by Atyc** [comment]
My bad - I had a global gitignore that I didn't know about.
The icon is in your initial commit. Not really sure why.

**Comment by raulir** [comment]
CMS inside update doesn't touch .gitignore, so if you have a very old version (before 27th april 2017 :) ), then you may have cache without leading slash in there.

**Comment by raulir** [comment]
Issue resolved, added gitignore negative line to override any ignoring of this directory.
