### ISSUE TITLE
admin main menu dropdown submenus half-hidden

### ISSUE THREAD

**Issue by alarir** [raulir/bccms#267]
See screenshot:

![bug_menu_hidden](https://user-images.githubusercontent.com/8036371/42414074-4b81a22a-8236-11e8-8738-f9606d2d8fbc.png)

Firefox 61.0.1/latest Chrome

**Comment by raulir** [comment]
Noticed, that correct url for this page should be:

localhost/beyond/admin/cms_list/beyond__eventcategory/

List admin url without module is deprecated :)

**Comment by alarir** [comment]
Added "critical" because whole functionalities are hidden and therefore missing for non-technical end-users.

**Comment by raulir** [comment]
fixed
