### ISSUE TITLE
date input

### ISSUE THREAD

**Issue by raulir** [raulir/bccms#63]
New input for dates

**Comment by raulir** [comment]
semantic ui calendar?

**Comment by alarir** [comment]
Have used similar, https://uxsolutions.github.io/bootstrap-datepicker/

**Comment by alarir** [comment]
Wasn't aware before, but if defined as `<Input type="date" />` the modern browsers display some basic datepicker: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by raulir** [comment]
Implemented using https://flatpickr.js.org/ which didn't need any external dependencies :)
