### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by Atyc** [raulir/bccms#78]
It would be useful to have an input type like this.
It will simplify the work of the developer by not having to add different color schemes in the CSS and just leave the colours up to the designers.

This should be a separate input type, not tied to Tinymce.

Nice example here: http://www.eyecon.ro/colorpicker/

**Comment by raulir** [comment]
#13 is the same thing.

Reasons, why I started to use and prefer colour schemes were:

1. Designers didn't input the same colours to different places. Colours were shade different in different places and in the end they asked me to make them all the same.

To solve this thing I think that there should be a module variables json file. ( #79 ) 

And all the variables should show up on scss files as well (similarly to php templates). ( #51 )


2. When projects were handed over to the clients (as most of the projects), they didn't have a clue, what to put to these colour fields and found the CMS messy and hard to use :)

You can see a lot of panel settings css printed out to templates in older projects, like SC1, TOVF and PSE, but later I found that in long run using colour schemes with fixed colours was more productive and easier for end user.

I think that colour input would be a good idea, just I don't think that this could be used everywhere.

On the other hand, as this cms allows to make websites on different level of backend complexity and  userfriendliness, then this is a good idea to have this kind of new input.

**Comment by raulir** [comment]
solved with #13
